# 创建命名空间  ：kubectl create namespace xuxiaowei-cloud
# 创建 pod    ：kubectl apply -f sentinel-deployment.yaml
# 查看 pod    ：kubectl -n xuxiaowei-cloud get pod -o wide
# 查看 pod    ：kubectl -n xuxiaowei-cloud get pod -o wide
# 进入 pod    ：kubectl -n xuxiaowei-cloud exec -it pod名称 bash
# 编辑 pod    ：kubectl -n xuxiaowei-cloud edit deployment sentinel-deployment
# 删除 pod    ：kubectl -n xuxiaowei-cloud delete deployment sentinel-deployment

# https://kubernetes.io/zh-cn/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-deployment
  namespace: xuxiaowei-cloud
spec:
  selector:
    matchLabels:
      app: sentinel
  replicas: 2
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      containers:
        - name: sentinel
          # https://hub.docker.com/r/xuxiaoweicomcn/sentinel
          image: xuxiaoweicomcn/sentinel:v1.8.6-dragonwell8
          ports:
            - containerPort: 22222
          command:
            - "java"
          args:
            - "-Dserver.port=22222"
            - "-Dcsp.sentinel.dashboard.server=localhost:22222"
            - "-Dproject.name=sentinel-dashboard"
            - "-jar"
            - "sentinel-dashboard.jar"
          volumeMounts:
            # 时区
            - name: time-zone
              mountPath: /etc/localtime
      # https://kubernetes.io/zh-cn/docs/concepts/storage/volumes/
      volumes:
        # 时区
        - name: time-zone
          hostPath:
            path: /etc/localtime

---

# 创建 Service（不能指定 nodePort） ：kubectl -n xuxiaowei-cloud expose deployment sentinel-deployment --type=NodePort --name=sentinel-service
# 编辑 Service                    ：kubectl -n xuxiaowei-cloud edit service sentinel-service
# 删除 Service                    ：kubectl -n xuxiaowei-cloud delete service sentinel-service
# 查看 pod、Service               ：kubectl -n xuxiaowei-cloud get pod,svc -o wide

# https://kubernetes.io/zh-cn/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: sentinel-service
  namespace: xuxiaowei-cloud
spec:
  ports:
    - nodePort: 32222
      port: 22222
      protocol: TCP
      targetPort: 22222
  selector:
    app: sentinel
  type: NodePort
