# 创建命名空间  ：kubectl create namespace xuxiaowei-cloud
# 创建 pod    ：kubectl apply -f zipkin-deployment.yaml
# 查看 pod    ：kubectl -n xuxiaowei-cloud get pod -o wide
# 查看 pod 描述：kubectl -n xuxiaowei-cloud describe pod pod名称
# 进入 pod    ：kubectl -n xuxiaowei-cloud exec -it pod名称 bash
# 编辑 pod    ：kubectl -n xuxiaowei-cloud edit deployment zipkin-deployment
# 删除 pod    ：kubectl -n xuxiaowei-cloud delete deployment zipkin-deployment

# https://kubernetes.io/zh-cn/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  namespace: xuxiaowei-cloud
spec:
  selector:
    matchLabels:
      app: zipkin
  replicas: 2
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          # https://hub.docker.com/r/openzipkin/zipkin
          image: openzipkin/zipkin:2.24
          ports:
            - containerPort: 9411
          volumeMounts:
            # 时区
            - name: time-zone
              mountPath: /etc/localtime
      # https://kubernetes.io/zh-cn/docs/concepts/storage/volumes/
      volumes:
        # 时区
        - name: time-zone
          hostPath:
            path: /etc/localtime

---

# 创建 Service（不能指定 nodePort） ：kubectl -n xuxiaowei-cloud expose deployment zipkin-deployment --type=NodePort --name=zipkin-service
# 编辑 Service                    ：kubectl -n xuxiaowei-cloud edit service zipkin-service
# 删除 Service                    ：kubectl -n xuxiaowei-cloud delete service zipkin-service
# 查看 pod、Service               ：kubectl -n xuxiaowei-cloud get pod,svc -o wide

# https://kubernetes.io/zh-cn/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: xuxiaowei-cloud
spec:
  ports:
    - nodePort: 30411
      port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    app: zipkin
  type: NodePort
