version: '1.0'
name: package
displayName: 打包
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
stages:
  - name: package
    displayName: 打包
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '8'
        mavenVersion: 3.6.3
        commands:
          - arch
          - echo 'public class Test {public static void main(String[] args) {System.out.println("os.arch：" + System.getProperty("os.arch"));System.out.println("os.version：" + System.getProperty("os.version"));}}' > Test.java
          - javac -encoding utf-8 -d . Test.java
          - java Test
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - target
        settings: []
        strategy:
          retry: '0'
strategy:
  blocking: false
permissions:
  - role: admin
    members: []
